/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description New token pair; role and permissions are re-read, so role changes apply on the next refresh.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Permissions
         * @description Справочник прав (роль `admin` имеет `*`).
         */
        get: operations["permissions_auth_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Objects
         * @description Вся статика одним ответом. Кэшируйте по `layout_version`: она растёт при каждом сохранении плана.
         */
        get: operations["get_objects_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layout */
        get: operations["get_layout_layout_get"];
        put?: never;
        /**
         * Save Layout
         * @description Сохраняет новую версию плана и применяет её к реестру: здания, помещения, геозоны, дороги, КПП и
         *     положение неподвижных датчиков. Новые датчики на плане создаются с типовыми порогами; убранные с плана
         *     отключаются. Worker, коннекторы и симулятор подхватывают изменения в течение минуты.
         */
        post: operations["save_layout_layout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensor-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sensor Types */
        get: operations["list_sensor_types_sensor_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sensors */
        get: operations["list_sensors_sensors_get"];
        put?: never;
        /**
         * Create Sensor
         * @description Без `thresholds` датчик получает типовые пороги своего типа. Начинает принимать данные сразу (коннекторы
         *     перечитывают реестр), симулятор подхватывает климат и движение в течение минуты.
         */
        post: operations["create_sensor_sensors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sensor */
        get: operations["get_sensor_sensors__sensor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Sensor */
        patch: operations["update_sensor_sensors__sensor_id__patch"];
        trace?: never;
    };
    "/sensors/{sensor_id}/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Thresholds
         * @description Новые пороги становятся следующей версией; старые закрываются (`valid_to`). Поле `version` во входе игнорируется.
         *     Worker перечитывает пороги каждые 30 с.
         */
        put: operations["set_thresholds_sensors__sensor_id__thresholds_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Create Sensors
         * @description CSV (колонки как у SensorCreate; `x`,`y` — координаты; `thresholds` — JSON-строка) или JSON-массив.
         *
         *     Всё или ничего: при любой ошибке не создаётся ни один датчик, ошибки возвращаются построчно.
         */
        post: operations["bulk_create_sensors_sensors_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sensor History
         * @description Шаг выбирается по длине периода: до 1 ч — сырые точки, до суток — минутные агрегаты, дальше — часовые.
         */
        get: operations["sensor_history_sensors__sensor_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vehicles */
        get: operations["list_vehicles_vehicles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicle_id}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vehicle Route
         * @description Трек машины по ГЛОНАСС; длинные периоды прореживаются до ~2000 точек (последняя точка в интервале).
         */
        get: operations["vehicle_route_vehicles__vehicle_id__route_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitelist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Whitelist
         * @description Пропуска и номера. ФИО видны только с правом `people:view_pii` (охрана, админ), остальным — маскированные.
         */
        get: operations["list_whitelist_whitelist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live State
         * @description Снимок текущего состояния; дальше изменения приходят по `WS /ws/live`.
         */
        get: operations["live_state_state_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Новые сверху. `from`/`to` — по времени открытия.
         */
        get: operations["list_alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack Alert
         * @description Подтвердить: эскалация останавливается, тревога остаётся живой до нормализации или ручного закрытия.
         */
        post: operations["ack_alert_alerts__alert_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Alert
         * @description Закрыть вручную. Если условие всё ещё выполняется, worker откроет новую тревогу.
         */
        post: operations["resolve_alert_alerts__alert_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comment Alert */
        post: operations["comment_alert_alerts__alert_id__comment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kpi
         * @description Показатели за период (по умолчанию — последний час).
         */
        get: operations["kpi_kpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Heatmap
         * @description Загруженность территории по ГЛОНАСС: сколько замеров попало в каждую ячейку сетки.
         */
        get: operations["heatmap_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Replay
         * @description Треки всех машин за окно (до 6 ч) с шагом `step` и тревоги этого окна — для таймлайна воспроизведения.
         */
        get: operations["replay_replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoints */
        get: operations["endpoints_connectors_endpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys */
        get: operations["list_keys_connectors_keys_get"];
        put?: never;
        /**
         * Issue Key
         * @description Выпустить ключ. Сам ключ возвращается **только в этом ответе**; коннекторы примут его в течение ~5 с.
         */
        post: operations["issue_key_connectors_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Key
         * @description Отозвать ключ. Коннекторы перестают его принимать в течение 30 с (интервал обновления их кэша).
         */
        delete: operations["revoke_key_connectors_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/rejections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rejections
         * @description Последние отклонённые сообщения (stream:dlq), новые сверху: что пришло и почему не принято.
         */
        get: operations["rejections_connectors_rejections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict/{sensor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Predict Sensor
         * @description Прогноз по метрике датчика (тренд, аномалия, время до выхода за пороги); для машин — ещё и до ТО.
         */
        get: operations["predict_sensor_predict__sensor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Predict All
         * @description Риски по всем датчикам типа: сначала самые срочные. По умолчанию — только требующие внимания.
         */
        get: operations["predict_all_predict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trips
         * @description Рейсы, новые сверху. Активный рейс у машины — не больше одного.
         */
        get: operations["list_trips_trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicle_id}/trip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Trip
         * @description Текущий рейс машины (последний незавершённый), иначе последний завершённый; null — рейсов не было.
         */
        get: operations["current_trip_vehicles__vehicle_id__trip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Доступность хранилищ; 503, если какое-то недоступно.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Id */
            id: number;
            /**
             * Rule Id
             * @example rule-cold-storage-temp
             */
            rule_id: string;
            /** Rule Version */
            rule_version: number;
            kind: components["schemas"]["AlertKind"];
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["AlertStatus"];
            /**
             * Title
             * @example Перегрев холодного склада
             */
            title: string;
            /**
             * Message
             * @example Температура 9.4 °C выше критического порога 8.0 °C
             */
            message: string;
            /**
             * Sensor Id
             * @example clim-wh2-storage
             */
            sensor_id?: string | null;
            /** Vehicle Id */
            vehicle_id?: string | null;
            /**
             * Building Id
             * @example b-wh2
             */
            building_id?: string | null;
            /**
             * Zone Id
             * @example r-wh2-storage
             */
            zone_id?: string | null;
            /**
             * Value
             * @example 9.4
             */
            value?: number | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Last Seen At
             * Format: date-time
             * @description Последнее событие, подтвердившее алерт (дедупликация)
             */
            last_seen_at: string;
            /** Ack At */
            ack_at?: string | null;
            /** Ack By */
            ack_by?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Escalation Level
             * @description Растёт по таймеру, пока алерт не подтверждён
             * @default 0
             */
            escalation_level: number;
        };
        /** AlertAction */
        AlertAction: {
            /** Comment */
            comment?: string | null;
        };
        /**
         * AlertKind
         * @enum {string}
         */
        AlertKind: "threshold" | "geozone" | "schedule" | "whitelist" | "speed" | "offline" | "breakdown";
        /** AlertPage */
        AlertPage: {
            /** Items */
            items: components["schemas"]["Alert"][];
            /** Total */
            total: number;
        };
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "open" | "ack" | "resolved";
        /** AlertsKpi */
        AlertsKpi: {
            /** Opened */
            opened: number;
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
            /** Top Rules */
            top_rules: components["schemas"]["RuleCount"][];
            /**
             * Mean Ack S
             * @description Среднее время от открытия до подтверждения
             */
            mean_ack_s: number | null;
            /** Open Now */
            open_now: number;
        };
        /** ApiKey */
        ApiKey: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Key Prefix
             * @description Первые символы ключа: по ним ключ узнают в логах и DLQ
             */
            key_prefix: string;
            /**
             * Sensor Types
             * @description null — любой тип датчиков
             */
            sensor_types?: components["schemas"]["SensorType"][] | null;
            /** Rate Limit Per Min */
            rate_limit_per_min: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** ApiKeyCreate */
        ApiKeyCreate: {
            /**
             * Name
             * @example Шлюз климата, склад №2
             */
            name: string;
            /** Sensor Types */
            sensor_types?: components["schemas"]["SensorType"][] | null;
            /**
             * Rate Limit Per Min
             * @default 6000
             */
            rate_limit_per_min: number;
        };
        /** ApiKeyIssued */
        ApiKeyIssued: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Key Prefix
             * @description Первые символы ключа: по ним ключ узнают в логах и DLQ
             */
            key_prefix: string;
            /**
             * Sensor Types
             * @description null — любой тип датчиков
             */
            sensor_types?: components["schemas"]["SensorType"][] | null;
            /** Rate Limit Per Min */
            rate_limit_per_min: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Revoked At */
            revoked_at: string | null;
            /**
             * Key
             * @description Показывается один раз; в базе хранится только SHA-256
             */
            key: string;
        };
        /** Body_bulk_create_sensors_sensors_bulk_post */
        Body_bulk_create_sensors_sensors_bulk_post: {
            /** File */
            file: string;
        };
        /** Building */
        Building: {
            /**
             * Id
             * @example b-wh2
             */
            id: string;
            /**
             * Site Id
             * @description Площадка, на которой стоит здание
             * @example s-podolsk
             */
            site_id?: string | null;
            /**
             * Name
             * @example Склад №2 (холодный)
             */
            name: string;
            /**
             * Building Type
             * @enum {string}
             */
            building_type: "office" | "warehouse" | "production" | "garage";
            /** Floors */
            floors: number;
            geometry: components["schemas"]["PolygonGeometry"];
        };
        /** BuildingTraffic */
        BuildingTraffic: {
            /** Building Id */
            building_id: string;
            /** Name */
            name: string;
            /**
             * Entries
             * @description Проходов внутрь по СКУД
             */
            entries: number;
            /** People Now */
            people_now: number;
        };
        /** BulkResult */
        BulkResult: {
            /** Dry Run */
            dry_run: boolean;
            /** Total */
            total: number;
            /** Valid */
            valid: number;
            /**
             * Created
             * @description Сколько датчиков создано; 0 при dry_run или при любой ошибке
             */
            created: number;
            /** Errors */
            errors: components["schemas"]["BulkRowError"][];
        };
        /** BulkRowError */
        BulkRowError: {
            /**
             * Row
             * @description Номер строки, начиная с 1 (без заголовка CSV)
             */
            row: number;
            /**
             * Field
             * @example type
             */
            field?: string | null;
            /**
             * Message
             * @example Input should be 'anpr_camera', 'access_control', ...
             */
            message: string;
        };
        /** Checkpoint */
        Checkpoint: {
            /**
             * Id
             * @example cp-1
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Checkpoint Type
             * @enum {string}
             */
            checkpoint_type: "vehicle" | "pedestrian";
            /** Zone Id */
            zone_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * Endpoints
         * @description Где устройства и шлюзы подключаются к уровню коннекторов (адреса снаружи, для инструкций).
         */
        Endpoints: {
            /**
             * Http Base
             * @example http://localhost:8001
             */
            http_base: string;
            /**
             * Mqtt Host
             * @example localhost
             */
            mqtt_host: string;
            /**
             * Mqtt Port
             * @example 1883
             */
            mqtt_port: number;
            /**
             * Api Key Header
             * @default X-API-Key
             */
            api_key_header: string;
            /**
             * Mqtt Key Property
             * @description MQTT 5 user property с ключом
             * @default x-api-key
             */
            mqtt_key_property: string;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Value */
            value: number;
        };
        /** GateKpi */
        GateKpi: {
            /**
             * Entries
             * @description Въезды в зону КПП-1 по ГЛОНАСС
             */
            entries: number;
            /** Exits */
            exits: number;
            /**
             * Plates Recognized
             * @description Распознаваний номеров камерами КПП
             */
            plates_recognized: number;
            /**
             * Bucket Minutes
             * @description Шаг by_hour: 5 мин (период до 3 ч), 60 (до 2 суток), 1440
             * @default 60
             */
            bucket_minutes: number;
            /**
             * By Hour
             * @description `hour` — начало интервала длиной bucket_minutes
             */
            by_hour: components["schemas"]["HourCount"][];
        };
        /**
         * Geo
         * @description Point in local plan coordinates, metres from the site origin (south-west corner).
         */
        Geo: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Floor
             * @description Этаж внутри здания; null — улица
             */
            floor?: number | null;
        };
        /**
         * Georef
         * @description Привязка локальных метров к WGS84: точка (0, 0) плана = (origin_lat, origin_lon).
         */
        Georef: {
            /** Origin Lat */
            origin_lat: number;
            /** Origin Lon */
            origin_lon: number;
            /**
             * Rotation Deg
             * @default 0
             */
            rotation_deg: number;
        };
        /** Geozone */
        Geozone: {
            /**
             * Id
             * @example z-gate
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Zone Type
             * @enum {string}
             */
            zone_type: "gate" | "docks" | "parking" | "restricted" | "speed";
            /** Speed Limit Kmh */
            speed_limit_kmh?: number | null;
            geometry: components["schemas"]["PolygonGeometry"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatCell */
        HeatCell: {
            /**
             * X
             * @description Центр ячейки, м
             */
            x: number;
            /** Y */
            y: number;
            /** Count */
            count: number;
        };
        /** Heatmap */
        Heatmap: {
            /** Cell M */
            cell_m: number;
            /** Source */
            source: string;
            /** Max Count */
            max_count: number;
            /** Cells */
            cells: components["schemas"]["HeatCell"][];
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Min */
            min: number;
            /** Avg */
            avg: number;
            /** Max */
            max: number;
        };
        /** HourCount */
        HourCount: {
            /**
             * Hour
             * Format: date-time
             */
            hour: string;
            /** Entries */
            entries: number;
            /** Exits */
            exits: number;
        };
        /** KpiResponse */
        KpiResponse: {
            /**
             * Period From
             * Format: date-time
             */
            period_from: string;
            /**
             * Period To
             * Format: date-time
             */
            period_to: string;
            /** Vehicles */
            vehicles: components["schemas"]["VehicleKpi"][];
            gate: components["schemas"]["GateKpi"];
            /** Buildings */
            buildings: components["schemas"]["BuildingTraffic"][];
            alerts: components["schemas"]["AlertsKpi"];
        };
        /** LayoutDocument */
        LayoutDocument: {
            /** Version */
            version: number;
            /**
             * Geojson
             * @description FeatureCollection в формате deploy/seed/layout.geojson
             */
            geojson: {
                [key: string]: unknown;
            };
        };
        /** LayoutUpdate */
        LayoutUpdate: {
            /**
             * Base Version
             * @description Версия, от которой редактировали; при расхождении — 409
             */
            base_version: number;
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
        };
        /** LineGeometry */
        LineGeometry: {
            /**
             * Type
             * @default LineString
             * @constant
             */
            type: "LineString";
            /** Coordinates */
            coordinates: [
                number,
                number
            ][];
        };
        /** LiveState */
        LiveState: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Sensors */
            sensors: components["schemas"]["SensorLive"][];
            /** Vehicles */
            vehicles: components["schemas"]["VehicleLive"][];
            /** Zones */
            zones: components["schemas"]["ZoneOccupancy"][];
            /** Open Alerts */
            open_alerts: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Maintenance */
        Maintenance: {
            /** Vehicle Id */
            vehicle_id: string;
            /** Plate */
            plate: string;
            /** Odometer Km */
            odometer_km: number;
            /** Service Interval Km */
            service_interval_km: number;
            /** Next Service Km */
            next_service_km: number;
            /** Remaining Km */
            remaining_km: number;
            /**
             * Km Per Day
             * @description Средний пробег в сутки по последним 24 ч
             */
            km_per_day?: number | null;
            /** Eta Days */
            eta_days: number | null;
            /** Summary */
            summary: string;
        };
        /** MetricSpec */
        MetricSpec: {
            /**
             * Key
             * @description Ключ поля в payload события
             * @example temperature_c
             */
            key: string;
            /**
             * Name
             * @example Температура
             */
            name: string;
            /**
             * Unit
             * @example °C
             */
            unit?: string | null;
            /**
             * Kind
             * @default number
             * @enum {string}
             */
            kind: "number" | "bool" | "string";
        };
        /**
         * ObjectsResponse
         * @description Вся статика одним ответом: план, реестр датчиков и машин. Фронт кэширует по layout_version.
         */
        ObjectsResponse: {
            /** Layout Version */
            layout_version: number;
            /**
             * Units
             * @default m
             * @constant
             */
            units: "m";
            /**
             * Extent
             * @description [x_min, y_min, x_max, y_max]
             */
            extent: [
                number,
                number,
                number,
                number
            ];
            georef: components["schemas"]["Georef"];
            /** Sites */
            sites: components["schemas"]["Site"][];
            /** Buildings */
            buildings: components["schemas"]["Building"][];
            /** Rooms */
            rooms: components["schemas"]["Room"][];
            /** Roads */
            roads: components["schemas"]["Road"][];
            /** Geozones */
            geozones: components["schemas"]["Geozone"][];
            /** Checkpoints */
            checkpoints: components["schemas"]["Checkpoint"][];
            /** Sensor Types */
            sensor_types: components["schemas"]["SensorTypeInfo"][];
            /** Sensors */
            sensors: components["schemas"]["Sensor"][];
            /** Vehicles */
            vehicles: components["schemas"]["Vehicle"][];
        };
        /** PolygonGeometry */
        PolygonGeometry: {
            /**
             * Type
             * @default Polygon
             * @constant
             */
            type: "Polygon";
            /**
             * Coordinates
             * @description Кольца полигона в метрах плана; первое — внешнее
             */
            coordinates: [
                number,
                number
            ][][];
        };
        /** PredictResponse */
        PredictResponse: {
            /** @description null — мало данных для прогноза */
            prediction?: components["schemas"]["Prediction"] | null;
            /** @description Только для ГЛОНАСС-трекеров */
            maintenance?: components["schemas"]["Maintenance"] | null;
        };
        /** Prediction */
        Prediction: {
            /** Sensor Id */
            sensor_id: string;
            /** Name */
            name: string;
            /** Metric */
            metric: string;
            /** Unit */
            unit: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Samples
             * @description Минутных точек за последние 24 ч
             */
            samples: number;
            /**
             * Current
             * @description Сглаженное (EWMA) значение за последние 15 мин
             */
            current: number;
            /**
             * Baseline Mean
             * @description Среднее за сутки без последних 15 мин
             */
            baseline_mean?: number | null;
            /** Baseline Std */
            baseline_std: number | null;
            /**
             * Zscore
             * @description Отклонение текущего значения от суточной нормы, в σ
             */
            zscore?: number | null;
            /**
             * Anomaly
             * @description |z| ≥ 3
             */
            anomaly: boolean;
            /**
             * Trend Per Hour
             * @description Наклон линейной регрессии (окно 30 мин, если тренд выражен, иначе 2 ч)
             */
            trend_per_hour?: number | null;
            /** Trend R2 */
            trend_r2: number | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "rising" | "falling" | "stable" | "unknown";
            /**
             * Eta Warning H
             * @description Часов до выхода за норму при текущем тренде (0 — уже вне нормы)
             */
            eta_warning_h?: number | null;
            /**
             * Eta Critical H
             * @description Часов до критической границы
             */
            eta_critical_h?: number | null;
            /** Bound Warning */
            bound_warning: number | null;
            /** Bound Critical */
            bound_critical: number | null;
            /**
             * Risk
             * @description critical: до крит. границы ≤ 2 ч; warning: до выхода из нормы ≤ 2 ч или аномалия; watch: ≤ 12 ч или |z| ≥ 2
             * @enum {string}
             */
            risk: "ok" | "watch" | "warning" | "critical";
            /** Summary */
            summary: string;
            /**
             * Forecast
             * @description Проекция тренда на 3 ч вперёд (шаг 15 мин)
             */
            forecast: components["schemas"]["ForecastPoint"][];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** Rejection */
        Rejection: {
            /**
             * Id
             * @description id записи в stream:dlq (время приёма)
             */
            id: string;
            /** Received At */
            received_at: string | null;
            /**
             * Reason
             * @example unknown_sensor
             */
            reason: string;
            /** Adapter */
            adapter: string | null;
            /**
             * Source
             * @description http | mqtt | worker
             */
            source?: string | null;
            /**
             * Api Key
             * @description Имя ключа, с которым пришло сообщение
             */
            api_key?: string | null;
            /** Detail */
            detail?: unknown;
            /**
             * Raw
             * @description Исходное сообщение (обрезано до 4 КБ)
             */
            raw?: string | null;
        };
        /** Replay */
        Replay: {
            /**
             * Period From
             * Format: date-time
             */
            period_from: string;
            /**
             * Period To
             * Format: date-time
             */
            period_to: string;
            /** Step S */
            step_s: number;
            /** Tracks */
            tracks: components["schemas"]["ReplayTrack"][];
            /**
             * Alerts
             * @description Тревоги, открытые в этом окне: для отметок на таймлайне
             */
            alerts: components["schemas"]["Alert"][];
        };
        /** ReplayTrack */
        ReplayTrack: {
            /** Vehicle Id */
            vehicle_id: string;
            /** Points */
            points: components["schemas"]["RoutePoint"][];
        };
        /**
         * Reporting
         * @description How often a device of the type reports: by time, plus "by exception" (on a significant change) in between.
         *
         *     Devices own the schedule (trackers and loggers are configured this way: Teltonika FMB defaults are
         *     300 s / 100 m / 10° moving and 3600 s parked; Russian rules for monitored transport ask for at least
         *     one fix every 30 s; GDP cold-chain practice logs temperature every 5 min). Connectors reject reports
         *     faster than `min_interval_s`; the offline rule fires after `offline_after_s` of silence.
         */
        Reporting: {
            /**
             * Heartbeat S
             * @description Отчёт при отсутствии изменений; null — только по событиям
             */
            heartbeat_s?: number | null;
            /**
             * Moving Period S
             * @description Транспорт в движении: не реже, чем раз в N с
             */
            moving_period_s?: number | null;
            /**
             * Idle Period S
             * @description Транспорт стоит с работающим двигателем
             */
            idle_period_s?: number | null;
            /**
             * On Change
             * @description Внеочередной отчёт при изменении метрики на величину (distance_m — пройденный путь, м)
             */
            on_change?: {
                [key: string]: number;
            };
            /**
             * Min Interval S
             * @description Чаще коннекторы не принимают (защита от «болтливых» устройств)
             * @default 0
             */
            min_interval_s: number;
            /**
             * Offline After S
             * @description Молчание дольше — датчик «нет связи»
             */
            offline_after_s?: number | null;
        };
        /** Road */
        Road: {
            /**
             * Id
             * @example road-main
             */
            id: string;
            /** Name */
            name: string;
            /** Width M */
            width_m: number;
            /** Speed Limit Kmh */
            speed_limit_kmh: number;
            /**
             * Road Class
             * @description site — проезд площадки, public — трасса между площадками
             * @default site
             * @enum {string}
             */
            road_class: "site" | "public";
            /**
             * Connects
             * @description Для трасс: две площадки
             * @example [
             *       "s-podolsk",
             *       "s-domodedovo"
             *     ]
             */
            connects?: string[] | null;
            geometry: components["schemas"]["LineGeometry"];
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "dispatcher" | "security" | "admin";
        /** Room */
        Room: {
            /**
             * Id
             * @example r-wh2-storage
             */
            id: string;
            /** Name */
            name: string;
            /** Building Id */
            building_id: string;
            /** Floor */
            floor: number;
            /**
             * Room Type
             * @example storage
             */
            room_type: string;
            geometry: components["schemas"]["PolygonGeometry"];
        };
        /** RoutePoint */
        RoutePoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Speed Kmh */
            speed_kmh: number;
        };
        /** RuleCount */
        RuleCount: {
            /** Rule Id */
            rule_id: string;
            /** Count */
            count: number;
        };
        /** Sensor */
        Sensor: {
            /**
             * Id
             * @example clim-wh2-storage
             */
            id: string;
            type: components["schemas"]["SensorType"];
            /**
             * Name
             * @example Климат, склад №2: хранение
             */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Building Id
             * @example b-wh2
             */
            building_id?: string | null;
            /**
             * Zone Id
             * @example r-wh2-storage
             */
            zone_id?: string | null;
            /** Floor */
            floor?: number | null;
            /** @description Точка установки; null для подвижных датчиков */
            geo?: components["schemas"]["Geo"] | null;
            /**
             * Vehicle Id
             * @description Для GNSS-трекера: машина, на которой он стоит
             */
            vehicle_id?: string | null;
            /**
             * Thresholds
             * @default []
             */
            thresholds: components["schemas"]["Threshold"][];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Is Mobile */
            is_mobile: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SensorCreate */
        SensorCreate: {
            /**
             * Id
             * @example clim-wh2-storage
             */
            id: string;
            type: components["schemas"]["SensorType"];
            /**
             * Name
             * @example Климат, склад №2: хранение
             */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Building Id
             * @example b-wh2
             */
            building_id?: string | null;
            /**
             * Zone Id
             * @example r-wh2-storage
             */
            zone_id?: string | null;
            /** Floor */
            floor?: number | null;
            /** @description Точка установки; null для подвижных датчиков */
            geo?: components["schemas"]["Geo"] | null;
            /**
             * Vehicle Id
             * @description Для GNSS-трекера: машина, на которой он стоит
             */
            vehicle_id?: string | null;
            /**
             * Thresholds
             * @default []
             */
            thresholds: components["schemas"]["Threshold"][];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** SensorHistory */
        SensorHistory: {
            /** Sensor Id */
            sensor_id: string;
            /** Metric */
            metric: string;
            /**
             * Step
             * @description raw — сырые точки; 1m/1h — агрегаты
             * @enum {string}
             */
            step: "raw" | "1m" | "1h";
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
        };
        /** SensorLive */
        SensorLive: {
            /**
             * Sensor Id
             * @example clim-wh2-storage
             */
            sensor_id: string;
            type: components["schemas"]["SensorType"];
            /** Building Id */
            building_id?: string | null;
            status: components["schemas"]["SensorStatus"];
            /** Last Seen */
            last_seen: string | null;
            /**
             * Values
             * @description Последний payload датчика
             * @example {
             *       "humidity_pct": 61,
             *       "temperature_c": 4.2
             *     }
             */
            values: {
                [key: string]: number | boolean | string;
            };
        };
        /**
         * SensorStatus
         * @enum {string}
         */
        SensorStatus: "ok" | "warning" | "critical" | "offline";
        /**
         * SensorType
         * @enum {string}
         */
        SensorType: "anpr_camera" | "access_control" | "gnss" | "motion" | "climate" | "smoke";
        /** SensorTypeInfo */
        SensorTypeInfo: {
            id: components["schemas"]["SensorType"];
            /**
             * Name
             * @example Климат (температура и влажность)
             */
            name: string;
            /**
             * Is Mobile
             * @description Подвижный датчик: позиция приходит в событиях, а не задана на плане
             */
            is_mobile: boolean;
            /** Metrics */
            metrics: components["schemas"]["MetricSpec"][];
            /** @description Частота передачи данных устройствами этого типа */
            reporting: components["schemas"]["Reporting"];
        };
        /**
         * SensorUpdate
         * @description Частичное обновление: передаются только меняемые поля. Пороги — отдельным PUT /sensors/{id}/thresholds.
         */
        SensorUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Building Id */
            building_id?: string | null;
            /** Zone Id */
            zone_id?: string | null;
            /** Floor */
            floor?: number | null;
            geo?: components["schemas"]["Geo"] | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "warning" | "critical";
        /**
         * Site
         * @description Площадка предприятия: завод, РЦ, склад. Площадки разнесены по региону, между ними — дороги общего пользования.
         */
        Site: {
            /**
             * Id
             * @example s-podolsk
             */
            id: string;
            /**
             * Name
             * @example Завод «Подольск»
             */
            name: string;
            /**
             * Site Type
             * @default plant
             * @enum {string}
             */
            site_type: "plant" | "dc" | "cold_store";
            /** Address */
            address?: string | null;
            /**
             * Gate
             * @description Въезд (КПП) в метрах плана
             */
            gate?: [
                number,
                number
            ] | null;
            geometry: components["schemas"]["PolygonGeometry"];
        };
        /**
         * Threshold
         * @description Пороги одной метрики. Норма — [min, max]; вне нормы — warning; вне [critical_min, critical_max] — critical.
         */
        Threshold: {
            /**
             * Metric
             * @example temperature_c
             */
            metric: string;
            /**
             * Nominal
             * @description Номинальное значение
             * @example 4
             */
            nominal?: number | null;
            /**
             * Min
             * @example 2
             */
            min?: number | null;
            /**
             * Max
             * @example 6
             */
            max?: number | null;
            /**
             * Critical Min
             * @example 0
             */
            critical_min?: number | null;
            /**
             * Critical Max
             * @example 8
             */
            critical_max?: number | null;
            /**
             * Version
             * @description Версия порога; алерт хранит версию, по которой сработал
             * @default 1
             */
            version: number;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Время жизни access-токена, секунд
             */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        /**
         * Trip
         * @description Рейс по путевому листу: откуда, куда, что везём. Приходит из транспортной системы через коннекторы.
         */
        Trip: {
            /**
             * Id
             * @description Номер путевого листа
             * @example ПЛ-2026-000123
             */
            id: string;
            /**
             * Vehicle Id
             * @example v-truck-1
             */
            vehicle_id: string;
            /**
             * Plate
             * @example А123ВС77
             */
            plate: string;
            /**
             * Origin Site Id
             * @example s-podolsk
             */
            origin_site_id: string;
            /**
             * Destination Site Id
             * @example s-chekhov
             */
            destination_site_id: string;
            /**
             * Route Id
             * @description Трасса между площадками
             * @example route-chekhov-podolsk
             */
            route_id?: string | null;
            /**
             * Cargo
             * @example Металлоконструкции
             */
            cargo: string;
            /**
             * Weight T
             * @example 12.4
             */
            weight_t: number;
            /** Pallets */
            pallets?: number | null;
            /**
             * Temperature Mode
             * @example -18…-22 °C
             */
            temperature_mode?: string | null;
            /**
             * Driver Name
             * @description ФИО; маскируется без права people:view_pii
             */
            driver_name?: string | null;
            status: components["schemas"]["TripStatus"];
            /** Planned Departure */
            planned_departure?: string | null;
            /** Departed At */
            departed_at?: string | null;
            /** Eta */
            eta?: string | null;
            /** Arrived At */
            arrived_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TripStatus
         * @enum {string}
         */
        TripStatus: "planned" | "loading" | "en_route" | "unloading" | "done";
        /** User */
        User: {
            /** Id */
            id: number;
            /**
             * Username
             * @example dispatcher
             */
            username: string;
            /**
             * Full Name
             * @example Иванов И. И.
             */
            full_name: string;
            role: components["schemas"]["Role"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vehicle */
        Vehicle: {
            /**
             * Id
             * @example v-truck-1
             */
            id: string;
            /**
             * Plate
             * @example А123ВС77
             */
            plate: string;
            kind: components["schemas"]["VehicleKind"];
            /**
             * Model
             * @example КАМАЗ 65115
             */
            model: string;
            /**
             * Sensor Id
             * @description GNSS-трекер машины
             * @example gnss-truck-1
             */
            sensor_id: string;
            /**
             * Carrier
             * @example ООО «ТрансЛогистик»
             */
            carrier?: string | null;
            /**
             * Home Site Id
             * @description Площадка базирования
             * @example s-podolsk
             */
            home_site_id?: string | null;
        };
        /**
         * VehicleKind
         * @enum {string}
         */
        VehicleKind: "truck" | "loader" | "car";
        /** VehicleKpi */
        VehicleKpi: {
            /** Vehicle Id */
            vehicle_id: string;
            /** Plate */
            plate: string;
            /**
             * Mileage Km
             * @description По одометру трекера за период
             */
            mileage_km: number;
            /**
             * Moving Min
             * @description Скорость > 1 км/ч
             */
            moving_min: number;
            /**
             * Idle Min
             * @description Стоит с работающим двигателем
             */
            idle_min: number;
            /**
             * Stopped Min
             * @description Стоит с заглушенным двигателем
             */
            stopped_min: number;
            /**
             * Utilization Pct
             * @description Доля времени в движении; всё считается только на территории
             */
            utilization_pct: number;
        };
        /** VehicleLive */
        VehicleLive: {
            /**
             * Vehicle Id
             * @example v-truck-1
             */
            vehicle_id: string;
            /** Sensor Id */
            sensor_id: string;
            status: components["schemas"]["VehicleStatus"];
            geo: components["schemas"]["Geo"];
            /** Speed Kmh */
            speed_kmh: number;
            /** Heading Deg */
            heading_deg: number;
            /** Fuel Pct */
            fuel_pct?: number | null;
            /** Engine On */
            engine_on: boolean;
            /**
             * Zone Id
             * @description Геозона, в которой сейчас машина
             */
            zone_id?: string | null;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
        };
        /** VehicleRoute */
        VehicleRoute: {
            /** Vehicle Id */
            vehicle_id: string;
            /** Points */
            points: components["schemas"]["RoutePoint"][];
        };
        /**
         * VehicleStatus
         * @enum {string}
         */
        VehicleStatus: "moving" | "idle" | "stopped" | "offline";
        /** WhitelistEntry */
        WhitelistEntry: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "card" | "plate";
            /**
             * Value
             * @example P-000123
             */
            value: string;
            /**
             * Holder Name
             * @description ФИО; маскируется без права people:view_pii
             */
            holder_name?: string | null;
            /** Holder Org */
            holder_org?: string | null;
            /** Allowed Building Ids */
            allowed_building_ids?: string[] | null;
            /** Schedule Id */
            schedule_id?: string | null;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Active */
            active: boolean;
        };
        /** WhitelistPage */
        WhitelistPage: {
            /** Items */
            items: components["schemas"]["WhitelistEntry"][];
            /** Total */
            total: number;
        };
        /** ZoneOccupancy */
        ZoneOccupancy: {
            /**
             * Zone Id
             * @description Здание или помещение
             * @example b-wh1
             */
            zone_id: string;
            /**
             * People
             * @description Людей внутри по событиям СКУД вход/выход
             */
            people: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Wrong username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    permissions_auth_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_objects_objects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectsResponse"];
                };
            };
        };
    };
    get_layout_layout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutDocument"];
                };
            };
        };
    };
    save_layout_layout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutDocument"];
                };
            };
            /** @description The plan was saved by someone else since `base_version` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid plan; `detail` lists every problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_sensor_types_sensor_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorTypeInfo"][];
                };
            };
        };
    };
    list_sensors_sensors_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["SensorType"] | null;
                building_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sensor_sensors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"];
                };
            };
            /** @description Sensor id already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sensor_sensors__sensor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sensor_sensors__sensor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_thresholds_sensors__sensor_id__thresholds_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Threshold"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_create_sensors_sensors_bulk_post: {
        parameters: {
            query?: {
                /** @description Только проверить, ничего не создавать */
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_bulk_create_sensors_sensors_bulk_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sensor_history_sensors__sensor_id__history_get: {
        parameters: {
            query: {
                /** @description Числовая метрика типа датчика, напр. temperature_c */
                metric: string;
                /** @description По умолчанию — час назад */
                from?: string | null;
                /** @description По умолчанию — сейчас */
                to?: string | null;
            };
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vehicles_vehicles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"][];
                };
            };
        };
    };
    vehicle_route_vehicles__vehicle_id__route_get: {
        parameters: {
            query?: {
                /** @description По умолчанию — час назад */
                from?: string | null;
                /** @description По умолчанию — сейчас */
                to?: string | null;
            };
            header?: never;
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleRoute"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_whitelist_whitelist_get: {
        parameters: {
            query?: {
                kind?: string | null;
                /** @description Поиск по номеру пропуска / гос. номеру */
                q?: string | null;
                active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitelistPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_state_state_live_get: {
        parameters: {
            query?: {
                /** @description "site" — объекты на улице (машины) */
                building_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_alerts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AlertStatus"][] | null;
                severity?: components["schemas"]["Severity"][] | null;
                kind?: components["schemas"]["AlertKind"][] | null;
                sensor_id?: string | null;
                vehicle_id?: string | null;
                building_id?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_alert_alerts__alert_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Alert is not open */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_alert_alerts__alert_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Already resolved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comment_alert_alerts__alert_id__comment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kpi_kpi_get: {
        parameters: {
            query?: {
                /** @description По умолчанию — час назад */
                from?: string | null;
                /** @description По умолчанию — сейчас */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_heatmap_get: {
        parameters: {
            query?: {
                /** @description По умолчанию — час назад */
                from?: string | null;
                /** @description По умолчанию — сейчас */
                to?: string | null;
                /** @description Размер ячейки, м (сотни метров — обзор всего региона) */
                cell?: number;
                /** @description vehicles — все позиции; stops — где стоят */
                source?: "vehicles" | "stops";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Heatmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_replay_get: {
        parameters: {
            query?: {
                /** @description По умолчанию — час назад */
                from?: string | null;
                /** @description По умолчанию — сейчас */
                to?: string | null;
                /** @description Шаг выборки, с */
                step?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Replay"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoints_connectors_endpoints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Endpoints"];
                };
            };
        };
    };
    list_keys_connectors_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"][];
                };
            };
        };
    };
    issue_key_connectors_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyIssued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_connectors_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rejections_connectors_rejections_get: {
        parameters: {
            query?: {
                limit?: number;
                adapter?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rejection"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_sensor_predict__sensor_id__get: {
        parameters: {
            query?: {
                /** @description По умолчанию: температура для климата, топливо для трекеров */
                metric?: string | null;
            };
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_all_predict_get: {
        parameters: {
            query?: {
                sensor_type?: components["schemas"]["SensorType"];
                risk_at_least?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prediction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips_trips_get: {
        parameters: {
            query?: {
                vehicle_id?: string | null;
                /** @description true — незавершённые рейсы */
                active?: boolean | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_trip_vehicles__vehicle_id__trip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
