"""region: trips, road class, vehicle home site

Revision ID: 0ede8225617d
Revises: 38cf0863b427
Create Date: 2026-10-09 11:51:20.693770
"""

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0ede8225617d'
down_revision = '38cf0863b427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Waybill number'),
    sa.Column('vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('origin_site_id', sa.String(length=64), nullable=False),
    sa.Column('destination_site_id', sa.String(length=64), nullable=False),
    sa.Column('cargo', sa.String(length=256), nullable=False),
    sa.Column('weight_t', sa.Float(), nullable=False),
    sa.Column('pallets', sa.Integer(), nullable=True),
    sa.Column('temperature_mode', sa.String(length=64), nullable=True, comment='Reefer cargo, e.g. «-18…-22 °C»'),
    sa.Column('driver_name', sa.String(length=128), nullable=True, comment='ПДн: маскируется для ролей без доступа'),
    sa.Column('status', sa.Enum('planned', 'loading', 'en_route', 'unloading', 'done', name='tripstatus', native_enum=False, length=32), nullable=False),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_trips_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_index('ix_trips_vehicle_updated', 'trips', ['vehicle_id', sa.literal_column('updated_at DESC')], unique=False)
    op.add_column('roads', sa.Column('road_class', sa.String(length=16), server_default='site', nullable=False, comment='site | public'))
    op.add_column('roads', sa.Column('connects', postgresql.ARRAY(sa.String(length=64)), nullable=True, comment='Public roads: the two sites'))
    op.add_column('vehicles', sa.Column('home_site_id', sa.String(length=64), nullable=True, comment='Site from the plan where it is based'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'home_site_id')
    op.drop_column('roads', 'connects')
    op.drop_column('roads', 'road_class')
    op.drop_index('ix_trips_vehicle_updated', table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
