"""initial schema

Revision ID: 38cf0863b427
Revises: 
Create Date: 2026-10-08 20:32:49.287288
"""

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision = '38cf0863b427'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='First chars of the key, to find it'),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('sensor_types', postgresql.ARRAY(sa.String(length=32)), nullable=True, comment='null = any type'),
    sa.Column('rate_limit_per_min', sa.Integer(), server_default='6000', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_prefix', name=op.f('uq_api_keys_key_prefix'))
    )
    op.create_geospatial_table('buildings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('building_type', sa.String(length=32), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=0, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings'))
    )
    op.create_geospatial_index('idx_buildings_geom', 'buildings', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('checkpoints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=16), nullable=False, comment='vehicle | pedestrian'),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=0, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkpoints'))
    )
    op.create_geospatial_index('idx_checkpoints_geom', 'checkpoints', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('roads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='LINESTRING', srid=0, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roads'))
    )
    op.create_geospatial_index('idx_roads_geom', 'roads', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('roles',
    sa.Column('id', sa.Enum('dispatcher', 'security', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Europe/Moscow', nullable=False),
    sa.Column('intervals', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='[{"days": [1..7 ISO weekday], "start": "HH:MM", "end": "HH:MM"}]; end < start crosses midnight'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_table('sensor_types',
    sa.Column('id', sa.Enum('anpr_camera', 'access_control', 'gnss', 'motion', 'climate', name='sensortype', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_mobile', sa.Boolean(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='[{key, name, unit, kind}]'),
    sa.Column('payload_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema of the event payload'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_types'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.Enum('truck', 'loader', 'car', name='vehiclekind', native_enum=False, length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('carrier', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('plate', name=op.f('uq_vehicles_plate'))
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('threshold', 'geozone', 'schedule', 'whitelist', 'speed', 'offline', 'breakdown', name='alertkind', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severity', native_enum=False, length=32), nullable=False, comment='Default; threshold rules escalate per value'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('schedule_id', sa.String(length=64), nullable=True),
    sa.Column('escalate_after_s', sa.Integer(), nullable=True, comment='Raise escalation_level if not acked'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_alert_rules_schedule_id_schedules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'version', name=op.f('pk_alert_rules'))
    )
    op.create_index('uq_alert_rules_current', 'alert_rules', ['id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_geospatial_table('sensors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('anpr_camera', 'access_control', 'gnss', 'motion', 'climate', name='sensortype', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=False, comment='Position comes with events (CH/Redis), geom is null'),
    sa.Column('building_id', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=0, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_sensors_building_id_buildings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type'], ['sensor_types.id'], name=op.f('fk_sensors_type_sensor_types')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_sensors_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors')),
    sa.UniqueConstraint('vehicle_id', name=op.f('uq_sensors_vehicle_id'))
    )
    op.create_geospatial_index('idx_sensors_geom', 'sensors', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_sensors_building_id'), 'sensors', ['building_id'], unique=False)
    op.create_index(op.f('ix_sensors_type'), 'sensors', ['type'], unique=False)
    op.create_index(op.f('ix_sensors_zone_id'), 'sensors', ['zone_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='argon2id'),
    sa.Column('role_id', sa.Enum('dispatcher', 'security', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('card', 'plate', name='whitelistkind', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False, comment='card_id or plate'),
    sa.Column('holder_name', sa.String(length=128), nullable=True, comment='ПДн: маскируется для ролей без доступа'),
    sa.Column('holder_org', sa.String(length=128), nullable=True),
    sa.Column('allowed_building_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True, comment='null = everywhere'),
    sa.Column('schedule_id', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_whitelist_schedule_id_schedules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whitelist'))
    )
    op.create_index('ix_whitelist_kind_value', 'whitelist', ['kind', 'value'], unique=False)
    op.create_geospatial_table('zones',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False, comment='room | geozone'),
    sa.Column('zone_type', sa.String(length=32), nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=0, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_zones_building_id_buildings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones'))
    )
    op.create_geospatial_index('idx_zones_geom', 'zones', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_zones_building_id'), 'zones', ['building_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('threshold', 'geozone', 'schedule', 'whitelist', 'speed', 'offline', 'breakdown', name='alertkind', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'ack', 'resolved', name='alertstatus', native_enum=False, length=32), server_default='open', nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=True),
    sa.Column('vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('building_id', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('dedup_key', sa.String(length=160), nullable=False, comment='rule_id:object_id, same as Redis alert:open key'),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ack_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['ack_by'], ['users.id'], name=op.f('fk_alerts_ack_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id', 'rule_version'], ['alert_rules.id', 'alert_rules.version'], name='fk_alerts_rule'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_alerts_sensor_id_sensors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_alerts_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_sensor_id'), 'alerts', ['sensor_id'], unique=False)
    op.create_index('ix_alerts_status_opened', 'alerts', ['status', sa.literal_column('opened_at DESC')], unique=False)
    op.create_index('uq_alerts_active_dedup', 'alerts', ['dedup_key'], unique=True, postgresql_where=sa.text("status <> 'resolved'"))
    op.create_table('layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_layouts_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_layouts')),
    sa.UniqueConstraint('version', name=op.f('uq_layouts_version'))
    )
    op.create_table('thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('critical_min', sa.Float(), nullable=True),
    sa.Column('critical_max', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_thresholds_sensor_id_sensors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thresholds')),
    sa.UniqueConstraint('sensor_id', 'metric', 'version', name=op.f('uq_thresholds_sensor_id'))
    )
    op.create_index('uq_thresholds_current', 'thresholds', ['sensor_id', 'metric'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_thresholds_current', table_name='thresholds', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('thresholds')
    op.drop_table('layouts')
    op.drop_index('uq_alerts_active_dedup', table_name='alerts', postgresql_where=sa.text("status <> 'resolved'"))
    op.drop_index('ix_alerts_status_opened', table_name='alerts')
    op.drop_index(op.f('ix_alerts_sensor_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_zones_building_id'), table_name='zones')
    op.drop_geospatial_index('idx_zones_geom', table_name='zones', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('zones')
    op.drop_index('ix_whitelist_kind_value', table_name='whitelist')
    op.drop_table('whitelist')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensors_zone_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_type'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_building_id'), table_name='sensors')
    op.drop_geospatial_index('idx_sensors_geom', table_name='sensors', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('sensors')
    op.drop_index('uq_alert_rules_current', table_name='alert_rules', postgresql_where=sa.text('is_current'))
    op.drop_table('alert_rules')
    op.drop_table('vehicles')
    op.drop_table('sensor_types')
    op.drop_table('schedules')
    op.drop_table('roles')
    op.drop_geospatial_index('idx_roads_geom', table_name='roads', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('roads')
    op.drop_geospatial_index('idx_checkpoints_geom', table_name='checkpoints', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('checkpoints')
    op.drop_geospatial_index('idx_buildings_geom', table_name='buildings', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('buildings')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
